name: Zip and Upload Python Lambda code to S3

on:  
  push:
    paths: 
    - 'Backend/**'

jobs:
  zip-and-s3-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: zip
        run: |
          cd Backend
          zip lambda.zip lambda.py
      - uses: jakejarvis/s3-sync-action@v0.3.1
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
            --exclude 'lambda.py'
            --exclude 'terraform/*' 
            --exclude 'README.md'
        env:
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_BACKEND }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './Backend'
